export enum ReserveStateEnum {
  REPAIR_INQUIRY = 'REPAIR_INQUIRY',
  REQUEST_USER = 'REQUEST_USER',
  INPROGRESS = 'INPROGRESS',
  DONE = 'DONE',
  EXPIRED = 'EXPIRED',
  CANCELLED_ADMIN = 'CANCELLED_ADMIN',
  CANCELLED_USER = 'CANCELLED_USER',
}
export enum ReserveHoursEnum {
  AT_8 = 8,
  AT_9 = 9,
  AT_10 = 10,
  AT_11 = 11,
}
